# Generated by Django 4.2.6 on 2023-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_rename_items_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantities',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
