# Generated by Django 4.2.6 on 2023-10-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0005_delete_cart'),
        ('Cart', '0007_alter_cart_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantMenu.menuitem'),
        ),
    ]
