# Generated by Django 4.2.6 on 2023-10-31 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0008_alter_cart_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
