# Generated by Django 4.2.6 on 2023-11-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cart", "0014_remove_cart_item_remove_cart_quantity_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
