# Generated by Django 4.2.6 on 2023-10-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_alter_menu_dish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
