# Generated by Django 4.2.6 on 2023-10-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_dish_dish_type_dish_restaurant_id_delete_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshours',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
