# Generated by Django 4.2.6 on 2023-10-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_dish_price_useraddress_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='MenuItem',
        ),
    ]
