# Generated by Django 4.2.6 on 2023-10-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_rename_dish_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
