# Generated by Django 4.2.6 on 2023-10-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='test',
        ),
    ]
