# Generated by Django 4.2.6 on 2023-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0003_remove_cart_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(upload_to='%Y/%m/%d/%H:%M:%S/', verbose_name='img'),
        ),
    ]
