# Generated by Django 4.2.6 on 2023-10-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantMenu', '0004_alter_menuitem_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
